site_name: NextCloudPi 說明文件
theme: readthedocs
pages:
    - 開始吧:
        - 首頁 & 概述: index.md
        - 如何安裝: Getting-Started/How-to-install-NextCloudPi.md
        - 如何在區域網路中訪問: Getting-Started/How-to-access-NextCloudPi.md
        - 如何在廣域網路中訪問: Getting-Started/How-to-access-from-outside-your-network.md
        - 如何使用 Berryboot 安裝 NCP (第一章): Getting-Started/Berryboot-install-NextCloudPi-on-an-external-drive-step-by-step.md
        - 如何使用 Berryboot 安裝 NCP (第二章): Getting-Started/BerryBoot-Instructions-for-NextCloudPi.md
        - 常見問題: Getting-Started/FAQ.md
        - 為什麼我的 Pi 運行速度那麼慢 ?: Getting-Started/Why-is-my-Pi-so-slow.md
        - 如何獲得幫助: Getting-Started/How-and-where-to-get-help.md
        - 如何安裝 & 開始使用 ncp docker: Getting-Started/How-to-get-started-with-NCP-docker.md
    - 配置: 
        - 新增其它語言: Configure/Add-a-new-language-to-ncp-web.md
        - 參考配置: Configure/Configuration-Reference.md
        - 設定外部 USB 磁碟機: Configure/How-to-configure-an-external-USB-drive-with-NextCloudPi.md
        - NCP-config: Configure/How-to-configure-NextCloudPi.md
        - 2FA 雙重認證: Configure/Two-Factor-Authentication-for-Nextcloud.md
        - Letsencrypt DNS (SSL): Configure/How-to-get-certificate-with-Letsencrypt-using-DNS-to-verify-domain.md
        - Letsencrypt closed ports: Configure/How-to-configure-Lets-Encrypt-with-closed-ports-80-and-443.md
        - 同步 NC 至 Android: Configure/Sync-Nextcloud-tasks-calendars-and-contacts-on-your-Android-device.md
        - 如何使用nc-snapshot進行備份和還原: Configure/How-to-backup-and-restore-using-nc-snapshot.md
    - 維護:
        - 啟用 SSH: Maintain/How-to-enable-SSH-using-nextcloudpi-config-or-ncp-web.md
        - 電子郵件設定: Maintain/Email-settings.md
        - 備份 & 復原: Maintain/How-to-backup-and-restore-a-NextCloudPi-instance-using-ncp-config.md
        - 自動備份: Maintain/How-to-periodically-backup-to-a-second-USB-drive-with-NextCloudPi.md
        - 貢獻: Maintain/Contribute.md
        - 開發環境: Maintain/Development-environment.md
        - 測試 NCP: Maintain/Testing-NextCloudPi.md
        - 測試版功能測試: Maintain/Workflow-and-testing-of-new-features.md
        - 更新 Lynis: Maintain/How-to-update-Lynis.md
        - 開發人員指南: Maintain/ncp-app-developer-guide.md
    - 一般:
        - 如何安裝 Webmin: General-Info/How-to-install-Webmin-to-nextcloudpi.md
        - 我該使用 Raspberry Pi 嗎?: General-Info/Should-I-use-a-Raspberry-Pi.md

